server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name nucleiui.integraksis.com;
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name nucleiui.integraksis.com;
    ssl_certificate     /etc/letsencrypt/live/nucleiui.integraksis.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nucleiui.integraksis.com/privkey.pem;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_stapling on;
    access_log /var/log/nginx/nucleiui.access.log;
    error_log /var/log/nginx/nucleiui.errors.log;
    client_max_body_size 100m;

    include /etc/letsencrypt/options-ssl-nginx.conf;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_read_timeout 600;
        proxy_send_timeout 600;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header X-Request-Id $pid-$msec-$remote_addr-$request_length;
    }
}